### PR TITLE
fix: update to latest Intellij products

### PR DESCRIPTION
**Pull request by tscharke**
- Runs with latest Intellij products (2024.2+)
- Add a list of compatible products
- Increase version of plugin

### CODE REVIEW

**Comment by tscharke** [comment]
@Flyrell: Feel free to take a look 😃 And if it suits you, feel free to update the plugin on the marketplace.

**Comment by Mateusz-H** [comment]
After building the plugin from your branch and installing it into webstorm, im stuck on tools/html attrubute folder settings 
image

And as we can see plugin seems to be build correctly with version (1.1.2) 
image

**Comment by tscharke** [comment]
Thanks @Mateusz-H  for your feedback 🫣 Can you tell me which version of webstorm you tested it with? I'll take a look at it...

**Comment by tscharke** [comment]
@Mateusz-H I just tried it again with my branch ([https://github.com/tscharke/html-attribute-folder/tree/bugs/update-to-latest-intellij-products](https://github.com/tscharke/html-attribute-folder/tree/bugs/update-to-latest-intellij-products)) and WebStorm 2024.2.

Both the function and the settings screen work perfectly.

Bildschirmfoto 2024-08-25 um 15 06 58
Bildschirmfoto 2024-08-25 um 15 07 18

I've created a new release for my branch, which is available for [download here](https://github.com/tscharke/html-attribute-folder/releases/download/v1.1.2/html-attribute-folder-1.1.2.zip
).

Perhaps you would like to try it out and install version 1.1.2 of this plugin manually?

**Comment by Mateusz-H** [comment]
@tscharke I'm very sorry for the inconvenience, I was using an older version of webstorm, after the update everything is fine.
image

**Comment by tscharke** [comment]
@Mateusz-H You don't have to apologise. I'm glad that it works for you now 😎

And I'm very happy about your interest 😊 

Have fun and certainly this version of the plug-in will soon be available on the marketplace 🤞🤞🤞

**Comment by Flyrell** [comment]
Hey guys, thanks for the update.

Honest talk, would any of you be interested in maintaining this plugin further? As I'm quite busy, I feel the best think I can do is to find someone who'd maintain it in the future.

Unfortunately, IntelliJ updates quite often breake the compatibility, so it's quite difficult to update it for me.

**Comment by Mateusz-H** [comment]
> Hey guys, thanks for the update.
> 
> Honest talk, would any of you be interested in maintaining this plugin further? As I'm quite busy, I feel the best think I can do is to find someone who'd maintain it in the future.
> 
> Unfortunately, IntelliJ updates quite often breake the compatibility, so it's quite difficult to update it for me.

I've never done anything in kotlin, however, I'm still looking for something to help me use tailwindcss (class wrap), so maybe a bigger contribution to html-attirbute-folder development can be beneficial to me.

**Comment by tscharke** [comment]
@Flyrell I use the plugin regularly because it is a useful tool for me 😎

As you can already see, I already support you. And yes, I can imagine officially supporting this project 😊

In my fork I've already automated the construction of a release. Maybe we could still install the publication on the marketplace here?

And would it be really cool if @Mateusz-H  was also there and we did it together? What do you think?

**Comment by Flyrell** [comment]
It's already published, just pending approval on JetBrains' side.

Screenshot 2024-08-27 at 08 36 19

And, of course, the more the merrier 😄 

My plan would be to give you guys access to the repo, and as soon as I'm going to be able (or if you want to) set up the pipelines for building, signing & publishing the plugin when the tag is created. Maybe having some unit tests wouldn't hurt as well.

**Pull request merged**
